baseURL: "https://adityatelange.github.io/hugo-PaperMod/"
title: Derek Hart, Ph.D.
copyright: "Â© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
paginate: 5
enableEmoji: true
theme: [hugo-PaperMod]
params:
  defaultTheme: auto
  ShowWordCount: true
  math: true
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true
    title: "Derek Hart, Ph.D. ðŸ§¬"
    subtitle: "Hello! I'm a data wrangler at the NIH, helping modernize the Sequence Read Archive. I earned my doctorate at Georgia Tech in 2022, specializing in single-molecule biophysics."
    imageUrl: "images/me.jpg"
    imageWidth: "300px"
    imageHeight: "400px"
    buttons:
      - name: "Blog"
        url: "posts"
      - name: "CV"
        url: "cv"
      - name: "Projects"
        url: "projects"
  socialIcons: # optional
    - name: "email"
      url: "mailto:derekjordanhart@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/derekhart0/"
    - name: "github"
      url: "https://github.com/dhart31"
    - name: "orcid"
      url: "https://orcid.org/0009-0001-2549-513X"
menu:
  main:
    - name: "Blog"
      url: "posts"
    - name: "CV"
      url: "cv"
    - name: "Projects"
      url: "projects"
    - name: "Search"
      url: "search"
outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

